# NHTS 2017

```{r libs, eval = TRUE, echo = FALSE, results = "hide", warning = FALSE, error = FALSE, message = FALSE, fig.width = 8}
rm(list=ls())
library("tidyverse")
library("xtable")
library("ggplot2")
library("ggpubr")
library("devtools")
install("~/ITHIM/")
library("ITHIM")
opts_knit$set(root.dir = "~/NHTS/")
RDS <- FALSE
```
## Trip Data
```{r trippub, eval = !RDS, echo = TRUE, results = "show", warning = FALSE, error = FALSE, message = FALSE, results="asis"}

trippub.raw <- read.csv(file = "./data/trippub.csv", stringsAsFactors = FALSE)

trippub <- with(trippub.raw,{
    data.frame(HOUSEID = as.character(HOUSEID),
               PERSONID = as.character(PERSONID),
#               TDCASEID = TDCASEID,
               TRPTRANS = factor(ifelse(TRPTRANS %in% c(-9,-8,-7,97), NA, TRPTRANS), levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20), labels = c("walk","cycle","car","SUV","van","pickup truck","golf cart/Segway","motorcycle/moped","RV","school bus","public or commuter bus","paratransit/Dial-a-ride","private/charter/tour/shuttle bus","city-to-city bus (Greyhound, Megabus)","Amtrak/commuter rail","subway/elevated/light rail/street car","taxi/limo/Uber/Lyft", "rental car/Zipcar/Car2Go", "airplane","boat/ferry/water taxi")),
               TRVLCMIN = ifelse(as.numeric(TRVLCMIN) < 0, as.numeric(NA), as.numeric(TRVLCMIN)), stringsAsFactors = FALSE)
#               URBRUR  = as.factor(URBRUR),
#               MSACAT = as.factor(MSACAT),
#               MSA = ifelse(MSASIZE %in% 1:5, TRUE, FALSE),
#               TRPMILES = as.numeric(TRPMILES)
})

trippub <- with(trippub,{
    data.frame(houseID=HOUSEID, subjectID=PERSONID, duration = TRVLCMIN, mode = TRPTRANS, stringsAsFactors = FALSE)
})

trippub <- trippub %>% select(houseID, subjectID, duration, mode)
```
## Person Data
```{r perpub, eval = !RDS, echo = TRUE, results = "show", warning = FALSE, error = FALSE, message = FALSE, results="asis"}
perpub <- read.csv(file = "./data/perpub.csv", stringsAsFactors = FALSE)
perpub <- with(perpub,{
                    data.frame(HOUSEID = as.character(HOUSEID),
                               PERSONID = as.character(PERSONID),
                               SEX = as.factor(ifelse(R_SEX=="1", "M", ifelse(R_SEX=="2", "F", NA))),
                               AGE = ifelse(as.numeric(R_AGE) < 0, as.numeric(NA), as.numeric(R_AGE)), stringsAsFactors = FALSE)
})

perpub <- with(perpub,{
    data.frame(houseID=HOUSEID, subjectID=PERSONID, sex = SEX, age = factor(ifelse(!is.na(AGE), ifelse(AGE <= 18, "child", ifelse(AGE <= 65, "adult", "senior")), NA), levels = c("child","adult","senior")), stringsAsFactors = FALSE)
    })

perpub <- perpub %>% select(houseID, subjectID, sex, age)
```
## Household Data
```{r hhpub, eval = !RDS, echo = TRUE, results = "show", warning = FALSE, error = FALSE, message = FALSE, results="asis"}
hhpub.raw <- read.csv(file = "./data/hhpub.csv", stringsAsFactors = FALSE)
hhpub <- with(hhpub.raw,{
                    data.frame(houseID = as.character(HOUSEID),
#                               BIKE = factor(ifelse(BIKE %in% c(-9,-8,-7), NA, BIKE), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               WALK = factor(ifelse(WALK %in% c(-9,-8,-7), NA, WALK), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               CAR = factor(ifelse(CAR %in% c(-9,-8,-7), NA, CAR), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               BUS = factor(ifelse(BUS %in% c(-9,-8,-7), NA, BUS), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               TAXI = factor(ifelse(TAXI %in% c(-9,-8,-7), NA, TAXI), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               TRAIN = factor(ifelse(TRAIN %in% c(-9,-8,-7), NA, TRAIN), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               PARA = factor(ifelse(PARA %in% c(-9,-8,-7), NA, PARA), levels = 1:5, labels = c("daily","a few times a week","a few times a month","a few times a year","never")),
#                               URBRUR = factor(URBRUR, levels = 1:2, labels = c("urban","rural")),
#                               #HH_CBSA = factor(ifelse(HH_CBSA == "XXXXX", NA, as.character(HH_CBSA))),
                               HH_CBSA = as.character(HH_CBSA),
                    HHSTATE = factor(as.character(HHSTATE)), stringsAsFactors = FALSE)
})

cbsaNames <- read.csv(file = "./data/cbsa2fipsxw.csv", stringsAsFactors = FALSE)
cbsaNames <- cbsaNames %>% filter(!is.na(cbsacode)) %>% group_by(cbsacode) %>% summarise(cbsatitle = first(cbsatitle))

hhpub <- within(hhpub, {
    HH_CBSA <- ifelse(HH_CBSA == "XXXXX", paste0(HHSTATE,"-XXXXX"), as.character(HH_CBSA))
    HH_CBSA <- factor(HH_CBSA, levels = c(cbsaNames$cbsacode, paste0(levels(HHSTATE),"-XXXXX")), labels = c(as.character(cbsaNames$cbsatitle),paste0(levels(HHSTATE),"-XXXXX")))
})

hhpub <- hhpub %>% select(houseID, location = HH_CBSA)
```

```{r TravelSurvey, eval = !RDS, echo = TRUE, warning = FALSE, error = FALSE, message = FALSE}
NHTS <- new("TravelSurvey", person = perpub, trip = trippub, house = hhpub)
saveRDS(NHTS, file = "./R/data/NHTS.ts.rds")
```

```{r TravelSurvey2, eval = TRUE, echo = TRUE, warning = FALSE, error = FALSE, message = FALSE}
NHTS <- readRDS(file = "~/NHTS/R/data/NHTS.ts.rds")
inner_join(getTA(NHTS, type = "day"), getp0(NHTS, type = "day"), by = "location")
```

```{r TravelSurvey3, eval = TRUE, echo = TRUE, warning = FALSE, error = FALSE, message = FALSE}
hhpub.meta <- hhpub.raw %>% select(houseID = HOUSEID, BIKE, WALK) %>% mutate(houseID = as.character(houseID))

hhpub.meta <- within(hhpub.meta,{
    WALK.weekly = ifelse(WALK %in% c(-9,-8,-7), NA, ifelse(WALK %in% 1:2, TRUE, FALSE))
    BIKE.weekly = ifelse(BIKE %in% c(-9,-8,-7), NA, ifelse(BIKE %in% 1:2, TRUE, FALSE))
    ACTIVE.weekly = ifelse(WALK.weekly | BIKE.weekly, "active", "inactive")
})


```


```{r TravelSurvey3c, eval = TRUE, echo = TRUE, warning = FALSE, error = FALSE, message = FALSE}
ACTIVE.df <- inner_join(NHTS@house, hhpub.meta, by = "houseID") %>% group_by(location) %>% count(ACTIVE.weekly) %>% spread(ACTIVE.weekly, n, fill = 0) %>% mutate(p0 = inactive/(active+inactive)) %>% select(location, p0)

p0.df <- inner_join(ACTIVE.df, getp0(NHTS, type = "day"), by = "location", suffix = c(".survey",".data"))

p0.df %>%
 ggplot(aes(x = p0.data, y = p0.survey)) +
 geom_point(colour = "red") +
 geom_smooth(method = "lm", fill = NA, formula = y ~ x)

lmodel <- lm(p0.survey ~ p0.data, data = p0.df)
fAT <- 1/lmodel$coefficients["p0.data"]

UK <- readRDS(file = "~/CUSSH/R/data/UK.ts.rds")

TA <- rbind(getTA(NHTS, type = "day", fAT = fAT), getTA(UK, type = "week"))
p0 <- rbind(getp0(NHTS, type = "day", fAT = fAT), getp0(UK, type = "week"))

TA
p0

```
<!--~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--~~~~~~ ARCHIVE ~~~~~~~~~-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~-->

```{r join, eval = FALSE, echo = FALSE, results = "show", warning = FALSE, error = FALSE, message = FALSE, results="asis"}
NHTS.df <- dplyr::left_join(perpub, trippub, by = c("houseID","subjectID"))
NHTS.df <- full_join(NHTS.df, hhpub, by = "houseID")

NHTS.df <- within(NHTS.df, {
    id <- paste0(houseID,"-",subjectID)
    duration <- ifelse(is.na(duration) | duration == -9, 0, duration)
    mode <- mode
    location <- location
})

saveRDS(NHTS.list <- list(perpub = perpub, trippub = trippub, hhpub = hhpub, NHTS.df = NHTS.df), file = "./R/data/NHTS.list.rds")
```

```{r readRDS, eval = FALSE, echo = FALSE, results = "show", warning = FALSE, error = FALSE, message = FALSE, results="asis"}
NHTS.list <- readRDS(file = "./R/data/NHTS.list.rds")
```

```{r summaryPerpub, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.width = 8}
NHTS.list$perpub %>% group_by(location) %>% summarise(n = n()) %>% xtable(.) %>% print(.,type = "html", include.rownames = FALSE)
```
```{r histPerpub, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.height = 10}
sampleSize.df <- NHTS.list$NHTS.df %>% group_by(location) %>% summarise(n = n())

sampleSize.df <- within(sampleSize.df, location <- factor(location, levels = sampleSize.df$location[order(sampleSize.df$n)]))

sampleSize.df %>% ggplot(aes(x = location, y = n, fill = location)) + geom_bar(stat = "identity") + theme_bw() + labs(x = "", y = "", title = "Sample Size by State", subtitle = "NHTS 2017") + coord_flip() + theme(legend.position = "none") + scale_y_continuous(trans='log10')
```

```{r modeShare, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.width = 8}
modeShare.df <- NHTS.list$NHTS.df %>% group_by(mode) %>% summarise(duration = sum(duration))

modeShare.df <- within(modeShare.df, mode <- factor(mode, levels = modeShare.df$mode[order(modeShare.df$duration)]))

modeShare.df %>% ggplot(aes(x=mode, y = duration, fill = mode)) + geom_bar(stat = "identity") + theme_bw() + labs(x = "", y = "", title = "Total Minutes Traveled by Mode (Urban and Rural)", subtitle = "NHTS 2017") + theme(legend.position="none") + coord_flip() + scale_y_continuous(trans='log10')
```

```{r neverWalk, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.height = 20, fig.width = 10}

p0.df <- NHTS.list$hhpub %>% filter(!is.na(HH_CBSA)) %>% group_by(HH_CBSA, URBRUR) %>% summarise(p0 = sum(WALK == "never" & BIKE == "never", na.rm = TRUE)/sum(!is.na(WALK) & !is.na(BIKE)))

orderedLevels <- p0.df %>% filter( URBRUR == "urban" ) %>% arrange(p0) %>% select(HH_CBSA) %>% unlist() %>% as.character()
p0.df <- within(p0.df, HH_CBSA <- factor(HH_CBSA, level = orderedLevels))

p0.df %>% ggplot(aes(x=HH_CBSA, y = p0, fill = HH_CBSA)) + geom_bar(stat="identity", position = "dodge") + theme_bw() + labs(x = "", y = "", title = "Proportion of Households That Never Walk or Bike", subtitle = "NHTS 2017, Urban only (State-XXXXX is the group of all MSAs with pop. < 1 million)") + theme(legend.position="none") + coord_flip()  + facet_grid(. ~ URBRUR)
```

```{r WALK, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.height = 20, fig.width = 10}

NHTS.list$hhpub$HH_CBSA <- factor(NHTS.list$hhpub$HH_CBSA, levels = orderedLevels)

NHTS.list$hhpub %>% filter(!is.na(WALK)) %>% ggplot(aes(x=HH_CBSA, fill = WALK)) + geom_bar(position = "fill") + theme_bw() + labs(x = "", y = "", title = "WALK", subtitle = "NHTS 2017, Urban only (State-XXXXX is the group of all MSAs with pop. < 1 million)") + coord_flip() + facet_grid(. ~ URBRUR)
```


```{r BIKE, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.height = 20, fig.width = 10}
NHTS.list$hhpub %>% filter(!is.na(BIKE)) %>% ggplot(aes(x=HH_CBSA, fill = BIKE)) + geom_bar(position = "fill") + theme_bw() + labs(x = "", y = "", title = "BIKE", subtitle = "NHTS 2017, Urban only (State-XXXXX is the group of all MSAs with pop. < 1 million)") + coord_flip() + facet_grid(. ~ URBRUR)
```


```{r nMSA, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis", fig.height = 20, fig.width = 10}
foo <- NHTS.list$hhpub %>% group_by(HH_CBSA) %>% summarise(n = n()) %>% arrange(1/n)
NHTS.list$hhpub <- within(NHTS.list$hhpub, HH_CBSA <- factor(HH_CBSA, levels = rev(foo$HH_CBSA)))

NHTS.list$hhpub %>% ggplot(aes(x=HH_CBSA, fill = URBRUR)) + geom_bar(stat = "count") + theme_bw() + labs(x = "", y = "", title = "", subtitle = "NHTS 2017") + coord_flip() + theme(legend.position="none")+ scale_y_continuous(trans='log10')
```


```{r normalCA, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.CA <- NHTS.list$NHTS.df %>% filter(location %in% c("CA")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.CA$logTA)
```
```{r normal2CA, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.CA <- within(qq.CA,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.CA$logTA)
```


```{r normalWI, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.WI <- NHTS.list$NHTS.df %>% filter(location %in% c("WI")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.WI$logTA)
```
```{r normal2WI, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.WI <- within(qq.WI,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.WI$logTA)
```


```{r normalNY, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.NY <- NHTS.list$NHTS.df %>% filter(location %in% c("NY")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.NY$logTA)
```
```{r normal2NY, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.NY <- within(qq.NY,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.NY$logTA)
```


```{r normalTX, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.TX <- NHTS.list$NHTS.df %>% filter(location %in% c("TX")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.TX$logTA)
```
```{r normal2TX, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.TX <- within(qq.TX,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.TX$logTA)
```


```{r normalGA, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.GA <- NHTS.list$NHTS.df %>% filter(location %in% c("GA")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.GA$logTA)
```
```{r normal2GA, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.GA <- within(qq.GA,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.GA$logTA)
```


```{r normalNC, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.NC <- NHTS.list$NHTS.df %>% filter(location %in% c("NC")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.NC$logTA)
```
```{r normal2NC, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.NC <- within(qq.NC,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.NC$logTA)
```


```{r normalSC, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.SC <- NHTS.list$NHTS.df %>% filter(location %in% c("SC")) %>% group_by(location, mode, id) %>% summarise( T = sum(duration) ) %>% filter( mode %in% c("walk","cycle") ) %>% spread(mode, T, fill = 0) %>% filter( (walk > 0) | (cycle > 0)) %>% mutate(logTA = log(7*(3*walk/60 + 6*cycle/60)))

ggqqplot(qq.SC$logTA)
```
```{r normal2SC, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results="asis"}
qq.SC <- within(qq.SC,{
    logTA <- logTA - rnorm(n = length(logTA), mean = 3, sd = 1)
})

ggqqplot(qq.SC$logTA)
```


```{r activityFile, eval = FALSE, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}
logTA.df <- NHTS.list$NHTS.df %>%
    group_by(location, mode, id) %>%
    summarise( T = sum(duration) ) %>%
    filter( mode %in% c("walk","cycle") ) %>%
    spread(mode, T, fill = 0) %>%
    filter( (walk > 0) | (cycle > 0)) %>%
    mutate(logTA = log(7*(3*walk/60 + 6*cycle/60))) %>%
    group_by(location) %>%
    summarise( meanlogTA = mean(logTA), sdlogTA = sd(logTA))

p0.df <- NHTS.list$hhpub %>%
    group_by(HHSTATE) %>%
    summarise(p0 = sum(WALK == "never" & BIKE == "never", na.rm = TRUE)/sum(!is.na(WALK) & !is.na(BIKE)))

activity.df <- inner_join(logTA.df, p0.df, by = c("location" = "HHSTATE"))

activity.df <- activity.df[,c(1,4,2,3)]
names(activity.df) <- c("ID","p0","meanlog","sdlog")
write.csv(activity.df, file = "./R/data/activity.states.baseline.csv", quote = FALSE, row.names = FALSE)

ggplot(activity.df, aes(x = 1 - p0, y = meanlog, colour = sdlog, label = ID)) + geom_point() + geom_text(aes(label = ID), hjust=0, vjust=0)

activity.scenario.df <- within(activity.df,{
    p0 <- ifelse(p0 - 0.01 < 0, 0, p0 - 0.01)
})

write.csv(activity.scenario.df, file = "./R/data/activity.states.scenario.csv", quote = FALSE, row.names = FALSE)

PAF.df <- CRA(activityFile.baseline="~/NHTS/R/data/activity.states.baseline.csv", activityFile.scenario="~/NHTS/R/data/activity.states.scenario.csv")

melt(data.frame(state = rownames(PAF.df), PAF.df)) %>% ggplot(aes(x = state, y = value, group = variable)) + geom_line(aes(colour = variable))

```
